// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKmeS0SHq8TLdlnYpN4-cUBd4jlCnt34',
    appId: '1:677178690715:web:f95130cbbe9d4764300a3e',
    messagingSenderId: '677178690715',
    projectId: 'eco-comunidade',
    authDomain: 'eco-comunidade.firebaseapp.com',
    databaseURL: 'https://eco-comunidade-default-rtdb.firebaseio.com',
    storageBucket: 'eco-comunidade.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTrbEFznXpqDYPAQXN9ddEQ-uXaICpYwI',
    appId: '1:677178690715:android:959ad2c8b9ba059f300a3e',
    messagingSenderId: '677178690715',
    projectId: 'eco-comunidade',
    databaseURL: 'https://eco-comunidade-default-rtdb.firebaseio.com',
    storageBucket: 'eco-comunidade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsyUYoDisLTc0cYL2gEFvPNQ5K27OJO20',
    appId: '1:677178690715:ios:8395b1cb7b7c7322300a3e',
    messagingSenderId: '677178690715',
    projectId: 'eco-comunidade',
    databaseURL: 'https://eco-comunidade-default-rtdb.firebaseio.com',
    storageBucket: 'eco-comunidade.appspot.com',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsyUYoDisLTc0cYL2gEFvPNQ5K27OJO20',
    appId: '1:677178690715:ios:8395b1cb7b7c7322300a3e',
    messagingSenderId: '677178690715',
    projectId: 'eco-comunidade',
    databaseURL: 'https://eco-comunidade-default-rtdb.firebaseio.com',
    storageBucket: 'eco-comunidade.appspot.com',
    iosBundleId: 'com.example.projectFirebase',
  );

}